Bug 16733: Adjust other debian scripts using PERL5LIB
This patch makes the following changes:

koha-foreach, koha-upgrade-schema (shell scripts):
[1] Read default file
[2] Include helper functions
[3] Add call to adjust_paths_dev_install
[4] Replace hardcoded path by $PERL5LIB

koha-shell (perl script):
[1] Remove hardcoded lib path
[2] Add a sub that reads PERL5LIB from default or koha-conf, just as the
    shell scripts do.

koha-plack (shell script), plack.psgi:
[1] Add call to adjust_paths_dev_install
[2] Remove hardcoded lib path
[3] Add installer path to PERL5LIB, remove it from plack.pgsi

koha-sitemap (shell script):
[1] Add call to adjust_paths_dev_install
[2] Remove hardcoded lib path
[3] Add installer path to PERL5LIB
[4] Adjust path for call to sitemap cron job

koha-start-sip (shell script):
[1] Read default file
[2] Include helper functions
[3] Add call to adjust_paths_dev_install
[4] Adjust path to C4/SIP

koha-stop-sip (shell script):
[1] Remove KOHA_CONF and PERL5LIB (not needed to stop the daemon)
[2] Same for paths in daemon client options

NOTE: Script debian/scripts/koha-upgrade-to-3.4 has been left out
intentionally.

Test plan:
[1] Regular install:
    Run koha-foreach echo Hi
    Run koha-upgrade-schema yourinstance
    Run koha-shell yourinstance
    If you have plack, run koha-plack --start|--stop yourinstance
    Run koha-sitemap --generate yourinstance
    Run koha-start-sip yourinstance
    Run koha-stop-sip yourinstance

[2] Dev install [yourinstance] with <dev_install> in koha-conf.xml:
    Run koha-upgrade-schema yourinstance
    Run koha-shell yourinstance
    If you have plack: koha-plack --start|--stop yourinstance
    Run koha-sitemap --generate yourinstance
    Run koha-start-sip yourinstance
    Run koha-stop-sip yourinstance

[3] Git grep on koha/lib
    You should no longer see occurrences in debian/scripts except:
    koha-translate: see report 16749
    koha-upgrade-to-3.4: left out intentionally

[4] Git grep on koha/bin
    You should only see hits for lines with koha-functions in the
    debian scripts except:
    koha-upgrade-to-3.4: left out intentionally

Signed-off-by: Marcel de Rooy <m.de.rooy@rijksmuseum.nl>
Most scripts tested on Wheezy (although it would not matter much).
Plack script tested on Jessie.

Signed-off-by: Owen Leonard <oleonard@myacpl.org>

Signed-off-by: Jonathan Druart <jonathan.druart@bugs.koha-community.org>

Signed-off-by: Kyle M Hall <kyle@bywatersolutions.com>

diff --git a/debian/scripts/koha-start-sip b/debian/scripts/koha-start-sip
--- a/debian/scripts/koha-start-sip
+++ b/debian/scripts/koha-start-sip
@@ -18,6 +18,17 @@
 
 set -e
 
+# Read configuration variable file if it is present
+[ -r /etc/default/koha-common ] && . /etc/default/koha-common
+
+# include helper functions
+if [ -f "/usr/share/koha/bin/koha-functions.sh" ]; then
+    . "/usr/share/koha/bin/koha-functions.sh"
+else
+    echo "Error: /usr/share/koha/bin/koha-functions.sh not present." 1>&2
+    exit 1
+fi
+
 for name in "$@"
 do
     if [ ! -e /etc/koha/sites/${name}/koha-conf.xml ] ;
@@ -29,9 +40,17 @@ do
     echo "Starting SIP server for $name"
     mkdir -p /var/run/koha/${name}
     chown "${name}-koha:${name}-koha" /var/run/koha/${name}
+
+    adjust_paths_dev_install $name
     export KOHA_CONF PERL5LIB
     KOHA_CONF=/etc/koha/sites/${name}/koha-conf.xml
-    PERL5LIB="/usr/share/koha/lib"
+    # PERL5LIB has been read already
+    if [ "$DEV_INSTALL" = "" ]; then
+        LIBDIR=$KOHA_HOME/lib
+    else
+        LIBDIR=$KOHA_HOME
+    fi
+
     daemon \
         --name="$name-koha-sip" \
         --errlog="/var/log/koha/$name/sip-error.log" \
@@ -44,6 +63,6 @@ do
         --user="$name-koha.$name-koha" \
         -- \
         perl \
-        "/usr/share/koha/lib/C4/SIP/SIPServer.pm" \
+        "$LIBDIR/C4/SIP/SIPServer.pm" \
         "/etc/koha/sites/${name}/SIPconfig.xml"
 done
diff --git a/debian/scripts/koha-upgrade-schema b/debian/scripts/koha-upgrade-schema
--- a/debian/scripts/koha-upgrade-schema
+++ b/debian/scripts/koha-upgrade-schema
@@ -16,16 +16,31 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-
 set -e
 
+# Read configuration variable file if it is present
+[ -r /etc/default/koha-common ] && . /etc/default/koha-common
 
-update="/usr/share/koha/intranet/cgi-bin/installer/data/mysql/updatedatabase.pl"
+# include helper functions
+if [ -f "/usr/share/koha/bin/koha-functions.sh" ]; then
+    . "/usr/share/koha/bin/koha-functions.sh"
+else
+    echo "Error: /usr/share/koha/bin/koha-functions.sh not present." 1>&2
+    exit 1
+fi
+
+# Optionally use alternative paths for a dev install
+adjust_paths_dev_install $1
+if [ "$DEV_INSTALL" = "" ]; then
+    CGI_PATH=$KOHA_HOME/intranet/cgi-bin
+else
+    CGI_PATH=$KOHA_HOME
+fi
+
 for name in "$@"
 do
     echo "Upgrading database schema for $name"
     KOHA_CONF="/etc/koha/sites/$name/koha-conf.xml" \
-    PERL5LIB="/usr/share/koha/lib" \
-    "$update"
+    PERL5LIB=$PERL5LIB \
+    "$CGI_PATH/installer/data/mysql/updatedatabase.pl"
 done
-
