Bug 10101 - Follwup: fix param check
As Mason noted, there was an error on that line.

Sponsored-by: Universidad Nacional de Córdoba
Signed-off-by: Chris Cormack <chris@bigballofwax.co.nz>
Signed-off-by: Mason James <mtj@kohaaloha.com>
Signed-off-by: Jared Camins-Esakov <jcamins@cpbibliography.com>
(cherry picked from commit 7d09198659c92eda7046dee0f93e4caf2ec37096)

Signed-off-by: Jared Camins-Esakov <jcamins@cpbibliography.com>
(cherry picked from commit a4a270be68b7047ec6359847c1a462b7a82f6b67)

Signed-off-by: Chris Cormack <chris@bigballofwax.co.nz>

diff --git a/debian/scripts/koha-enable b/debian/scripts/koha-enable
--- a/debian/scripts/koha-enable
+++ b/debian/scripts/koha-enable
@@ -72,8 +72,20 @@ enable_instance()
         return 1
     fi
 }
+
+usage()
+{
+    local scriptname=$0
+    cat <<EOF
+Enables Koha instances.
+
+Usage: $scriptname instancename1 instancename2...
+
+EOF
+}
+
 # Parse command line.
-[ "$#" > 1 ] || die "Usage: $0 instancename..."
+[ $# -ge 1 ] || ( usage ; die "Missing instance name..." )
 
 restart_apache="no"
 
