Bug 10104 - Followup: fix param check
As noted by Mason on bug 10101, the check was not working for zero arguments.

Sponsored-by: Universidad Nacional de Córdoba

Signed-off-by: Mason James <mtj@kohaaloha.com>
Signed-off-by: Jared Camins-Esakov <jcamins@cpbibliography.com>
(cherry picked from commit ca118d57db383f5efebc4d53cba11ccc8af5c9a9)

Signed-off-by: Jared Camins-Esakov <jcamins@cpbibliography.com>

diff --git a/debian/scripts/koha-disable b/debian/scripts/koha-disable
--- a/debian/scripts/koha-disable
+++ b/debian/scripts/koha-disable
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# koha-disable -- disable Koha instances.
+# koha-disable - disable Koha instances.
 # Copyright 2010  Catalyst IT, Ltd
 # 
 # This program is free software: you can redistribute it and/or modify
@@ -73,8 +73,19 @@ disable_instance()
     fi
 }
 
+usage()
+{
+    local scriptname=$0
+    cat <<EOF
+Disables Koha instances.
+
+Usage: $scriptname instancename1 instancename2...
+
+EOF
+}
+
 # Parse command line.
-[ "$#" > 1 ] || die "Usage: $0 instancename..."
+[ $# -ge 1 ] || ( usage ; die "Missing instance name..." )
 
 restart_apache="no"
 
