Bug 13937: Add support for Z39.50 responder to the Debian scripts

diff --git a/debian/scripts/koha-list b/debian/scripts/koha-list
--- a/debian/scripts/koha-list
+++ b/debian/scripts/koha-list
@@ -39,6 +39,7 @@ show_instances()
               if instance_filter_email       $instance $show_email && \
                  instance_filter_letsencrypt $instance $show_letsencrypt && \
                  instance_filter_plack       $instance $show_plack && \
+                 instance_filter_z3950       $instance $show_z3950 && \
                  instance_filter_sip         $instance $show_sip; then
                     echo $instance
               fi ;;
@@ -47,6 +48,7 @@ show_instances()
                   if instance_filter_email       $instance $show_email && \
                      instance_filter_letsencrypt $instance $show_letsencrypt && \
                      instance_filter_plack       $instance $show_plack && \
+                     instance_filter_z3950       $instance $show_z3950 && \
                      instance_filter_sip         $instance $show_sip; then
                       echo $instance
                   fi
@@ -56,6 +58,7 @@ show_instances()
                   if instance_filter_email       $instance $show_email && \
                      instance_filter_letsencrypt $instance $show_letsencrypt && \
                      instance_filter_plack       $instance $show_plack && \
+                     instance_filter_z3950       $instance $show_z3950 && \
                      instance_filter_sip         $instance $show_sip; then
                       echo $instance
                   fi
@@ -153,6 +156,28 @@ instance_filter_email()
     return 1
 }
 
+instance_filter_z3950()
+{
+    local instancename=$1
+    local show_z3950=$2;
+
+    case $show_z3950 in
+        "all")
+            return 0 ;;
+        "enabled")
+            if is_z3950_enabled $instancename; then
+                return 0
+            fi ;;
+        "disabled")
+            if ! is_z3950_enabled $instancename; then
+                return 0
+            fi ;;
+    esac
+
+    # Didn't match any criteria
+    return 1
+}
+
 set_show()
 {
     local show_param=$1
@@ -208,6 +233,17 @@ set_show_sip()
     fi
 }
 
+set_show_z3950()
+{
+    local z3950_param=$1
+
+    if [ "$show_z3950" = "all" ]; then
+        show_z3950=$z3950_param
+    else
+        die "Error: --z3950 and --noz3950 are mutually exclusive."
+    fi
+}
+
 usage()
 {
     local scriptname=$0
@@ -228,6 +264,8 @@ Options:
     --noplack       Show instances with Plack disabled
     --letsencrypt   Show instances with letsencrypt enabled
     --noletsencrypt Show instances with letsencrypt disabled
+    --z3950         Show instances with Z39.50/SRU enabled
+    --noz3950       Show instances with Z39.50/SRU disabled
     --help | -h     Show this help
 
 The filtering options can be combined, and you probably want to do this
@@ -240,8 +278,9 @@ show_email="all"
 show_sip="all"
 show_plack="all"
 show_letsencrypt="all"
+show_z3950="all"
 
-args=$(getopt -l help,enabled,disabled,email,noemail,sip,nosip,plack,noplack,letsencrypt,noletsencrypt -o h -n $0 -- "$@")
+args=$(getopt -l help,enabled,disabled,email,noemail,sip,nosip,plack,noplack,letsencrypt,noletsencrypt,z3950,noz3950 -o h -n $0 -- "$@")
 set -- $args
 
 while [ ! -z "$1" ]
@@ -256,6 +295,8 @@ do
       --noplack) set_show_plack "disabled" ;;
   --letsencrypt) set_show_letsencrypt "enabled" ;;
 --noletsencrypt) set_show_letsencrypt "disabled" ;;
+        --z3950) set_show_z3950 "enabled" ;;
+      --noz3950) set_show_z3950 "disabled" ;;
       --enabled) set_show "enabled" ;;
      --disabled) set_show "disabled" ;;
               *) break;;
